# Generated by Django 3.2.5 on 2021-07-29 12:37

from django.db import migrations, models
import internship.utils
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('unique_id', models.CharField(default=internship.utils.unique_id_generator, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='verified status')),
                ('is_admin', models.BooleanField(default=False, help_text='Admin status')),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Superuser status')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to=internship.utils.user_image_upload_path)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
